export const INCREMENT_DATA = "INCREMENT_DATA";
export const DECREMENT_DATA = "DECREMENT_DATA";
export const COUNTER_ACTION_STARTED = "COUNTER_ACTION_STARTED";
export const COUNTER_ACTION_FINISHED = "COUNTER_ACTION_FINISHED";
